###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "pankaj",
    "password": "12121212"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "pankaj",
    "password": "12121212"
}



###




###




###